### ISSUE TITLE
Sketch

### ISSUE THREAD

**Issue by Cocorali** [BeryNice/cdmx-2018-06-bc-core-am-data-dashboard#2]
- [x] Editar fotos del sketch baja fidelidad en una sola img 
- [x] Subir img sketch baja fidelidad en README
- [x] Subir liga de sketch mediana fidelidad
- [x] Hacer una img del research de datadashboards en el mercado
- [x] Desglosar Data proporcionada en README
- [x] Hacer User Testing

**Comment by BeryNice** [comment]
terminando pendientes de sketch sprint 1
